### ISSUE TITLE
Delayed Channels and opening.

### ISSUE THREAD

**Issue by kluthen** [fuCtor/QAMQP#10] opened 2013-01-31 11:13 UTC
Hi,

I was trying to open new queues after client connection which resulted in ... nothing. (with no channel specified, doesn't work also with a channel number specified)
while reviewing the code, I happened to find my new queues put in delayed mode, waiting for the connection signal. 

Is there a design reason to have the opening of the channel only on client connection ?

Should I then open a trash channel at client connection and then use it's channel everytime I need to create a new queue connection ? (which seems to be working btw)

Sorry for the noobish question,

Thanks.

**Comment by fuCtor** [comment] 2013-02-01 09:21
Hi,
Thank you, yes it's error by design. In last commit I'm fixed that?, but i think I review this part and rewrite it later.
About channels.  I make decision that each channel can be assigned to only one queue or exchange. 
Before last fix, new channel  isn’t opened when client is already  connected. It was wrong.  Now when they are creating, client try open channel .  If client isn’t connected, they wait a signal.

Sorry for my English.

**Comment by kluthen** [comment] 2013-02-01 09:32
Hi ! Thanks for your quick answer. I'll pull your fix right away :)
I intend to open several queues and exchanges, and most of them after the initial connection. But i still don't see the need to open more than one channel. That is probably due to my lack of understanding of AMQP to begin with.
I'll document myself a bit more to stick more closely to the expected use of AMQP.

Thanks & Have a good day !

**Comment by fuCtor** [comment] 2013-02-01 09:51
One queue|exchange per channel make easy process recieving data.
For example: when I receive new message from queue,  I know only channel number.  And if channel would contains more then one queue, they both emit signal. Maybe exist solution, but now I make as is.

**Comment by kluthen** [comment] 2013-02-01 10:01
Uh, well I'll check on your code, I'm not sure to understand you well ;)

For example : 
- Queue 1 runs on Channel 1, consume tag_1
- Queue 2 runs on Channel 1, consume tag_2

If i receive a Message originally sent to Queue 1, will both Queue 1 and 2 emit the new Message Signal ? 

That's an academic question, at the moment my code doesn't have to handle separate message processing for each queues, it just need to process from a bunch of queues, which may vary with time. 

Thanks for your answer !

Otherwise you've done a real nice job with this QAMQP :+1:

**Comment by fuCtor** [comment] 2013-02-01 10:40
Yes, both.

Thanks, but it isn't full implementation of standart. Some methods isn't implemented yet :)

**Comment by kluthen** [comment] 2013-02-01 10:50
Okay ! Well i'll add a comment somewhere to be sure to remember that, just in case ;) 
I'm not sure how many channel i can have opened with RabbitMQ I'll have to check the doc, and use a distinct Channel for each Queue, to avoid having multiple times the same message being processed.

Thanks a million

**Closed as completed** 2013-02-01 11:09 UTC
